{
 "title": "dashboard_for_otrs",
 "time": { "from": "now-15d", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 4, "y": 0 },
   "content": "<img \n      src=\"#\"\n      alt=\"Company Logo\" \n      style=\"display:block; margin-left: auto; margin-right: auto;\">\n"
  },
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 3, "w": 6, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "select\n        create_time AS \"time\",\n        id\nfrom\n        acl\nwhere\n        $__timeFilter(create_time)\nORDER BY create_time"
    }
   ]
  },
  {
   "title": "Tickets em aberto por Atendente",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "select\n        concat(u.first_name, ' ',u.last_name) AS Nome,\n        count(t.id) Chamados\nfrom\n        ticket t,\n        queue q,\n        users u\nwhere\n        u.id = t.user_id and\n        q.id = t.queue_id and\n        t.ticket_state_id in (4,6,7,8) and\n        q.id = 2\ngroup by Nome"
    }
   ]
  },
  {
   "title": "Tickets em aberto por cliente",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 3 },
   "targets": [
    {
     "rawSql": "select\n      \tcc.name as \"Cliente\", \n      \tcount(t.id) as \"Tickets\"\nfrom\n      \tticket t,\n      \tqueue q,\n      \tticket_state ts,\n      \tcustomer_company cc\nwhere\n      \tt.customer_id = cc.customer_id and\n      \tt.queue_id = q.id and\n      \tt.ticket_state_id = ts.id and\n      \tt.ticket_state_id in (1,4,6,7,8) and\n      \tq.id = 2\ngroup by cc.name\norder by Tickets desc\n"
    }
   ]
  },
  {
   "title": "SLA Vencido",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "rawSql": "select \n    t.tn as Ticket,\n\t\tt.title as Título,\n\t\tt.create_time as Abertura,\n\t\tsec_to_time(to_seconds(now())-to_seconds(from_unixtime(t.escalation_solution_time))) as Atraso\nfrom \n\t\tticket t, \n\t\tqueue q, \n\t\tticket_state ts, \n\t\tsla s\nwhere \n    \tt.queue_id = q.id and \n    \tt.ticket_state_id = ts.id and\n    \tt.sla_id = s.id and \n    \tq.name <> 'Junk' and \n    \tts.id not in (2,3,10) and \n    \tfrom_unixtime(t.escalation_solution_time) < NOW() and \n    \tt.escalation_solution_time > 0;"
    }
   ]
  },
  {
   "title": "Tickets Novos",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select\n      count(*) Novos\nfrom\n      ticket\nwhere\n      ticket_state_id = 1;"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 13 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select\n        count(distinct t.id)\nfrom\n        ticket t\nwhere\n        date(t.create_time) = date(now())\n"
    }
   ]
  },
  {
   "title": "Ticket Backlog",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "# de tickets" }
   ],
   "targets": [
    {
     "rawSql": "select\n        $__timeGroup(t.create_time,'24h', 0) as time,\n        count(*) as qtd\nfrom\n        ticket t\ngroup by date(t.create_time)"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select\n        count(distinct t.id)\nfrom\n        ticket t,\n        ticket_history th\nwhere\n        t.id = th.ticket_id and\n        date(th.change_time) = date(now()) and\n        t.ticket_state_id in (2, 3, 10)\n"
    }
   ]
  }
 ]
}